#!/bin/sh
# -*- tcl -*-
# The next line is executed by /bin/sh, but not tcl \
exec tclsh "$0" ${1+"$@"}

# Test xvi's startup screen.
# Unlike the other tests, this doesn't use term_expect
# or utility functions from file "term" (except for start_vi and fail).

source term
start_vi

# Give it a second to refresh the display.
sleep 1

# The first line should be blank
if { [string trimright [$term get 1.0 1.end]] != "" } { fail 100 }

# Lines 2 to 23 should have a single ~ at the left edge
for {set i 2} {$i<$rows} {incr i} {
    if { [string trimright [$term get $i.0 $i.end]] != "~" } { fail 101 }
}

# The last line should just say "No File" but we don't really care about that
# if { [string trimright [$term get $rows.0 $rows.end]] != "No File" } { fail 102 }

# The cursor should be in the top left corner
if { $cur_row != 1 || $cur_col != 0 } { fail 103 }

exp_send ":q!\r"

exit 0
