#!/bin/sh
# -*- tcl -*-
# The next line is executed by /bin/sh, but not tcl \
exec tclsh "$0" ${1+"$@"}

# Issue NN: "yl" and "dl" when cursor is at end of line and
# dNl where N is a deimal number, near the end of the line.

source term
start_vi

# Check it started up OK
test 100 ""		1 0 [list "" "~"]

# Create a test pattern
test 101 "aabcde[esc]"	1 4 [list "abcde" "~"]

# Try a one-character yank at end of line
test 102 ylp		1 5 [list "abcdee" "~"]

# Restore abcde and try exactly the last 2 characters
test 103 {x$hd2l}	1 2 [list "abc" "~"]
# Check the prefix the other way round too
test 113 {p$h2dl}	1 2 [list "abc" "~"]

# Restore and sitting on the d, try taking more than there are
# (it should take 2)
test 104 {p$hd3l}	1 2 [list "abc" "~"]
test 114 {p$h3dl} 	1 2 [list "abc" "~"]

# Check that a numeric prefix is OK in the middle of the line too.
test 105 {p0l2dl}	1 1 [list "ade" "~"]

exp_send ":q!\r"

exit 0
