#!/bin/sh
# -*- tcl -*-
# The next line is executed by /bin/sh, but not tcl \
exec tclsh "$0" ${1+"$@"}

# Issue 93: Undoing "dl" leaves the cursor one place too far to the left.
#
# When undoing "dl", "d2l" etc, in the middle of a line, the cursor was left
# one place to the left compared to where it was.

source term
start_vi

# Check it started up OK
term_expect timeout { fail 100 } \
	{ screen_is 1 0 [list "" "~"] }

exp_send "aabcde\x1B"
tksleep
term_expect timeout { fail 101 } \
    { screen_is 1 4 [list "abcde" "~"] }

# Try a one-character delete in middle of the line
exp_send "0ll"
term_expect timeout { fail 102 } \
    { screen_is 1 2 [list "abcde" "~"] }
exp_send "dl"
term_expect timeout { fail 103 } \
    { screen_is 1 2 [list "abde" "~"] }
exp_send "u"
term_expect timeout { fail 104 } \
    { screen_is 1 2 [list "abcde" "~"] }

# Try deleting 2 characters
exp_send "2dl"
term_expect timeout { fail 105 } \
    { screen_is 1 2 [list "abe" "~"] }
exp_send "u"
term_expect timeout { fail 106 } \
    { screen_is 1 2 [list "abcde" "~"] }

# Try deleting the last 2 characters
exp_send "l"
tksleep
term_expect timeout { fail 107 } \
    { screen_is 1 3 [list "abcde" "~"] }
exp_send "2dl"
term_expect timeout { fail 108 } \
    { screen_is 1 2 [list "abc" "~"] }
exp_send "u"
term_expect timeout { fail 109 } \
    { screen_is 1 3 [list "abcde" "~"] }

exp_send ":q!\r"

exit 0
