#! /usr/bin/tclsh

# Issue 93: Undoing "dl" leaves the cursor one place to far to the left.
#
# WHen undoing "dl", "d2l" etc, in the middle of a line, the cursor was left
# one place to the left compare to where it was.

# Boilerplate

source term

# Tests begin

# Start xvi
exp_send "exec ../src/xvi 2>> errs\r"

# Check it started up OK
set timeout 1
term_expect timeout { exit 100 } \
	{ screen_is 1 0 [list "" "~"] }

exp_send "aabcde\x1B"
sleep 1
term_expect timeout { exit 101 } \
    { expr { [screen_is 1 4 [list "abcde" "~"]] } }

# Try a one-character delete in middle of the line
exp_send "Fc"
term_expect timeout { exit 102 } \
    { expr { [screen_is 1 2 [list "abcde" "~"]] } }
exp_send "dl"
term_expect timeout { exit 103 } \
    { expr { [screen_is 1 2 [list "abde" "~"]] } }
exp_send "u"
term_expect timeout { exit 104 } \
    { expr { [screen_is 1 2 [list "abcde" "~"]] } }

# Try deleting 2 characters
exp_send "2dl"
term_expect timeout { exit 105 } \
    { expr { [screen_is 1 2 [list "abe" "~"]] } }
exp_send "u"
term_expect timeout { exit 106 } \
    { expr { [screen_is 1 2 [list "abcde" "~"]] } }

# Try deleting the last 2 characters
exp_send "l"
sleep 1
term_expect timeout { exit 107 } \
    { expr { [screen_is 1 3 [list "abcde" "~"]] } }
exp_send "2dl"
term_expect timeout { exit 108 } \
    { expr { [screen_is 1 2 [list "abc" "~"]] } }
exp_send "u"
term_expect timeout { exit 109 } \
    { expr { [screen_is 1 3 [list "abcde" "~"]] } }

exp_send ":q!\r"

exit 0
