#!/bin/sh
# -*- tcl -*-
# The next line is executed by /bin/sh, but not tcl \
exec tclsh "$0" ${1+"$@"}

# Test that nul characters on the command line are ignored.

source term
start_vi

# Tests begin

# Check it started up OK
term_expect timeout { fail 100 } \
    { screen_is 1 0 [list "" "~"] }

# On the command line...
exp_send ":"

# ... nul should be ignored
exp_send "a\x00"
exp_send "b"
term_expect timeout { fail 101 } \
    { statusline_is ":ab" }

# ... as should Control-V nul
exp_send "c\x16\x00"
exp_send "d"
term_expect timeout { fail 102 } \
    { statusline_is ":abcd" }

exp_send "\b\b\b\bq!\r"

exit 0
