#!/bin/sh
# -*- tcl -*-
# The next line is executed by /bin/sh, but not tcl \
exec tclsh "$0" ${1+"$@"}

# Test that nul characters on the command line are ignored.

source term
start_vi

# Tests begin

# Check it started up OK
test 100 ""		1 0 [list "" "~"]

# On the command line...
exp_send ":"

# ... nul should be ignored
ctest 101 "a\x00b"	3 ":ab"

# ... as should Control-V nul
ctest 102 "c\x16\x00d"	5 ":abcd"

exp_send "\b\b\b\bq!\r"

exit 0
