#!/bin/sh
# -*- tcl -*-
# The next line is executed by /bin/sh, but not tcl \
exec tclsh "$0" ${1+"$@"}

#
# Check that it works without "Clear to end of line" capability.
#

set ::env(NOCE) 1

source term
start_vi

# Tests begin

# Check it started up OK
set timeout 1
term_expect timeout { fail 100 } \
	{ screen_is 1 0 [list "" "~"] }

exp_send "aabcde"
exp_send "\x1B"
tksleep
term_expect timeout { fail 101 } \
	{ screen_is 1 4 [list "abcde" "~"] }
exp_send "ylp"
term_expect timeout { fail 102 } \
	{ screen_is 1 5 [list "abcdee" "~"] }
exp_send "x"
term_expect timeout { fail 103 } \
	{ screen_is 1 4 [list "abcde" "~"] }

exp_send "q!\r"

exit 0

