#!/bin/sh
# -*- tcl -*-
# The next line is executed by /bin/sh, but not tcl \
exec tclsh "$0" ${1+"$@"}

# Test "showmode" parameter, placing "INSERT MODE"
# or "REPLACE MODE" 20 columns from the right of screen
# on the status line of the current window.

source term
start_vi

# Pick the "INSERT MODE" string from where it should be on the screen
proc getmode {} {
    global cols
    return [string trimright [string range [statusline] [expr $cols - 20] end]]
}

# Tests begin

# Start xvi
exp_send "exec ../src/xvi\r"

# Check it started up OK
term_expect timeout { exit 100 } \
    { screen_is 1 0 [list "" "~"] }

# Set the parameter. If it succeeds, the command should remain.
exp_send ":se showmode\r"
term_expect timeout { exit 101 } \
    { expr { [cursor_at 1 0] && [statusline_is ":se showmode"] } }

# See if the flag appears in insert mode
exp_send "i"
term_expect timeout { exit 102 } { expr { [getmode] eq "INSERT MODE" } }
# See if it disappears again
exp_send "\x1B"
term_expect timeout { exit 103 } { expr { [getmode] eq "" } }

# See if the flag appears in append mode
exp_send "a"
term_expect timeout { exit 104 } { expr { [getmode] eq "INSERT MODE" } }
# See if it disappears again
exp_send "\x1B"
term_expect timeout { exit 105 } { expr { [getmode] eq "" } }

# See if the flag appears in change mode
exp_send "C"
term_expect timeout { exit 106 } { expr { [getmode] eq "INSERT MODE" } }
# See if it disappears again
exp_send "\x1B"
term_expect timeout { exit 107 } { expr { [getmode] eq "" } }

# See if the flag appears in substitute mode
exp_send "s"
term_expect timeout { exit 108 } { expr { [getmode] eq "INSERT MODE" } }
# See if it disappears again
exp_send "\x1B"
term_expect timeout { exit 109 } { expr { [getmode] eq "" } }

# See if the flag appears in single-character replace mode
exp_send "r"
term_expect timeout { exit 110 } { expr { [getmode] eq "REPLACE MODE" } }
# See if it disappears after replacing one character
exp_send "a"
term_expect timeout { exit 111 } { expr { [getmode] eq "" } }

# See if the flag appears in multi-character replace mode
exp_send "R"
term_expect timeout { exit 112 } { expr { [getmode] eq "REPLACE MODE" } }
# See if it remains
exp_send "aaa"
term_expect timeout { exit 113 } { expr { [getmode] eq "REPLACE MODE" } }
# See if it disappears after pressing Escape
exp_send "\x1B"
term_expect timeout { exit 114 } { expr { [getmode] eq "" } }

exp_send ":q!\r"

exit 0
