#!/bin/sh
# -*- tcl -*-
# The next line is executed by /bin/sh, but not tcl \
exec tclsh "$0" ${1+"$@"}

# Issue 91, http://github.com/martinwguy/xvi/issues/91
#
# With tkterm, pending input chars prevent infinite map recursion
#
# When you say
#    :map x y
#    :map y x
#    xaa
# xvi should go into an infinite loop.
#
# but if you send them all in a single string, the x is ignored
# and an "a" is appended.

source term
start_vi

# Check it started up OK
test 100 ""			1 0 [list "" "~"]

exp_send ":map x y\r"
exp_send ":map y x\r"

test 10 "xaa" 1 0 [list "" "~"]

exp_send "\x03"

term_expect timeout { term_dump 102; exit 102 } \
    { expr { [statusline_is "Interrupted"] && [screen_is 1 0 [list "" "~"]] } }

exp_send ":q!\r"

exit 0
