#! /bin/sh

# Run all tests in the test suite.
#
# Each test is an executable file whose name starts with four digits and
# a hyphen, and exits 0 if it succeeds, 1 if the test cannot be run or
# 100-127 if it fails.
#
# This script exits with status 0 if all tests succeeded or were skipped,
# 1 if any failed.
#
#	Martin Guy <martinwguy@gmail.com>, March 2017.

status=0	# What to exit with; 0 means success.

for testfile in [0-9][0-9][0-9][0-9]-*
do
	printf "%-32.32s" "$testfile"
	if [ ! -x "$testfile" ]
	then	echo "DISABLED"
		continue
	fi

	./$testfile

	s=$?
	case $s in
	0)	echo "PASS" ;;
	1)	echo "SKIPPED" ;;
	*)	echo "FAILED with status $s"
		status=1 ;;
	esac
done

rm -f \#unnamed.*

exit $status
