#!/bin/sh
# -*- tcl -*-
# The next line is executed by /bin/sh, but not tcl \
exec tclsh "$0" ${1+"$@"}

#
# Check that xvi adapts properly to the interrupt character being something
# other than Control-C.
#

set intr Y

source tests/Interrupted
