#!/bin/sh
# -*- tcl -*-
# The next line is executed by /bin/sh, but not tcl \
exec tclsh "$0" ${1+"$@"}

# Check that [h] and [^h] match and don't match H when ignorecase is on
#
# Was https://github.com/martinwguy/xvi/issues/144

source scripts/term
start_vi

test 10 "aabcFcdcf[esc]0"	1 0 [list "abcFcdcf"]

test 11 ":se ignorecase\r/c\[f\]\r" 1 2 [list "abcFcdcf"]

# Matching [^f] shouldn't match the F any more and should end up on the "cd".
test 12 "0/c\[^f\]\r"		1 4 [list "abcFcdcf"]

stop_vi

exit 0
