#!/bin/sh
# -*- tcl -*-
# The next line is executed by /bin/sh, but not tcl \
exec tclsh "$0" ${1+"$@"}

# Test a weird bug. If you insert a character "iX[esc]" and then say "."
# it doesn't insert anything but tries to move left one space.

source scripts/term
start_vi

test 1 "i#[esc]."	1 0 "##"

stop_vi

exit 0
