#! /bin/sh
# -*- tcl -*-
# The next line is executed by /bin/sh, but not tcl \
exec tclsh "$0" ${1+"$@"}

# A quick script to tell you the key names used in "bind" commands.
#
# Just run this script, put the mouse in the Tk window that opens and
# press the key whose name you want to know.
#
# 	Martin Guy <martinwguy@gmail.com>, May 2017.

package require Tk
bind . <Key> { puts "<%K>" }
